name: mood

services:
  redis:
    image: redis:alpine
    restart: always
    networks:
      - redisnet
    ports:
      - "6379:6379"

  postgres:
    image: postgres
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  asynqmon:
    image: hibiken/asynqmon
    networks:
      - redisnet
    ports:
      - "8080:8080"
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis

  minio:
    ports:
      - 9000:9000
      - 9001:9001
    container_name: minio
    volumes:
      - ./minio/data:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"

  inbucket:
    container_name: inbucket
    ports:
      - 10000:9000
      - 2500:2500
      - 1100:1100
    image: inbucket/inbucket

networks:
  redisnet:

volumes:
  postgres_volume:
